### PR TITLE
Add symfony/debug to require-dev section

### PR DESCRIPTION
**Pull request by yceruto**
See https://github.com/symfony/symfony/pull/32270

### CODE REVIEW

**Comment by yceruto** [comment]
Although actual projects will still have problems updating to 4.4.

**Comment by nicolas-grekas** [comment]
Or we move the Debug class in ErrorCatcher

**Comment by nicolas-grekas** [comment]
Honestly I'm wondering if we want to keep the Debug component at all.

**Comment by yceruto** [comment]
Closing in favor of https://github.com/symfony/symfony/pull/32303

**Comment by Tobion** [comment]
We need to reopen this one right?

**Comment by yceruto** [comment]
It will not be necessary, the new `ErrorHandler` component will contain the `Debug` and other classes, see https://github.com/symfony/symfony/pull/32377

**Pull request closed without merging**
