### PR TITLE
Change App\Tests to App\Test

### PR DESCRIPTION
**Pull request by teohhanhui**
For consistency.

### CODE REVIEW

**Comment by sstok** [comment]
👎  `App\Test` is for code that is especially for testing (like test cases), Tests is what is used for a directory which holds tests.

**Comment by fabpot** [comment]
@sstok is right about our convention.

**Comment by teohhanhui** [comment]
But is the convention for the best? IMO we shouldn't have such easily confusable names...

**Comment by Pierstoval** [comment]
@teohhanhui It's a bit confusing too that the directory is named `tests` and the namespace is `Test`?

**Pull request closed without merging**
