### PR TITLE
Change tests namespace

### PR DESCRIPTION
**Pull request by mykiwi**
I would prefer to use `Tests\App\` rather than `App\Tests\`. Like in the Standard edition.  
What do you think?

### CODE REVIEW

**Comment by michalv8** [comment]
Tests are (crucial) part of yout app so I think it is more logical to keep them under `App\` namespace.

**Comment by fabpot** [comment]
👎 Tests are a subnamespace of your application.

**Comment by mykiwi** [comment]
I think it can be confusing. It's easier to explain than `App\*` is part of `src`, and `Tests\App\*` part of `tests/`. If for some reason a developer create a `src/Tests` directory with some logic inside, it will not be easy to see if it's a test, or part of the logic app.

**Comment by bocharsky-bw** [comment]
I think @mykiwi has a good point, `Tests\App` looks more robust because `App\Tests` could provide a conflict of namespaces if devs also create `src/Tests` directory, i.e. it's not so obvious that it could cause problems. If we use `App\Tests` we need always remember that we should avoid of creating `src/Tests/` dir.

**Comment by fabpot** [comment]
Closing this one. One application == one namespace. I don't buy the `App\Tests` namespace under `src/` issue. Namespace are almost always singular anyway (by practice and habits).

**Pull request closed without merging**
