### PR TITLE
Flex is not a dev req

### PR DESCRIPTION
**Pull request by fabpot**

### CODE REVIEW

**Comment by Pierstoval** [comment]
Actually, Flex has a good reason to be in `require-dev`: it's only used when running `reqiure` and `remove`, and has no reason to be executed in prod for example. It has no use with `composer install`, so a `composer install --no-dev` not running flex might be a good option IMO.

**Comment by gharlan** [comment]
It was discussed in #symfony-flex channel in slack.
Someone had this error:

> sh: symfony-cmd: command not found
> Script symfony-cmd handling the auto-scripts event returned with error code 127

and @stof replied with this:

> Flex should be handling such special script, but it won't work if it is not installed. A project using Flex must install the flex plugin as a normal requirement

**Comment by stof** [comment]
@Pierstoval it is also used when running auto scripts. And these ones are running on any install.

**Comment by dunglas** [comment]
Shouldn't this patch also be merged in the 3.3 branch?

**Comment by fabpot** [comment]
It's part of 3.3 as well.

**Comment by dunglas** [comment]
The patch has not been applied: https://github.com/symfony/skeleton/blob/3.3/composer.json#L13

**Comment by fabpot** [comment]
@dunglas That's embarrassing. Not sure how I messed up. Anyway, that's fixed now. Hopefully. Thanks for being pushy.

**Pull request merged**
