### PR TITLE
Move dotenv to "require"

### PR DESCRIPTION
**Pull request by nicolas-grekas**
This doesn't hurt anything and should ease using .env files without issues.

### CODE REVIEW

**Comment by Tobion** [comment]
👎 https://github.com/symfony/recipes/pull/491#discussion_r233655794

**Comment by nicolas-grekas** [comment]
Merging this would fix https://github.com/symfony/recipes/issues/497
I think we should merge.

**Comment by nicolas-grekas** [comment]
It's just adding the classes in `vendor/` so they could be used.
Promoting or not belongs to the doc, not to these technical things.

**Comment by fabpot** [comment]
From a user perspective (DX I would say), I'm ok with adding dotenv in require.

**Comment by Tobion** [comment]
You will not get an error if you forgot to define env vars. How can this be good DX? This is a security risk and bug festival.

**Comment by nicolas-grekas** [comment]
Yes you will, but at the container level. The .env files should provide default values, that's all. If you forgot tonset one of them, the app will react accordingly. Have dotenv in dev for the reason you mention is a very loose band-aid I wouldn't recommend anyone to rely on.

**Comment by Tobion** [comment]
So why would env vars me missing if it reads the .env file which sets the default values? What's your solution that is more reliable and works 100% of the cases?

**Comment by nicolas-grekas** [comment]
To verify that all env vars are defined, you could have a script that loads .env files and then ensures the SYMFONY_DOTENV_VARS is empty. This script would make your deployment fail if not.

**Comment by keradus** [comment]
To be honest, that extra script sounds like a workaround

**Pull request merged**
