### PR TITLE
Remove preferred-install configuration as it is the default

### LINKED ISSUE #205: Is preferred-install config still relevant?
[It apparently defaults to `dist`](https://getcomposer.org/doc/06-config.md#preferred-install).

Is it a discoverability thing or is it redundant?

### PR DESCRIPTION
**Pull request by MatTheCat**
Closes #205

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
Please rebase for 6.2

**Comment by nicolas-grekas** [comment]
Same on the website-skeleton please

**Review by fabpot — APPROVED** [review]

**Comment by MatTheCat** [comment]
Rebased and opened https://github.com/symfony/website-skeleton/pull/268

**Comment by fabpot** [comment]
Thank you @MatTheCat.

**Pull request merged**
